### PR TITLE
Fix templates to exec cucumber

### PR DESCRIPTION
**Pull request by YungSang**
It may be a wrong way to where you are going,
but I had to modify some templates to execute cucumber on Vagrant with v2.1.0.rc.12.

### CODE REVIEW

**Comment by zpatten** [comment]
Sorry everything was in flux when you grabbed master it looks like.  This has been re-worked already.

**Comment by zpatten** [comment]
Latest master is stable now; I'm only tweaking at this point.

**Comment by YungSang** [comment]
Oh Thanks!

**Comment by YungSang** [comment]
With v2.1.0.rc.14

I'd like to let you know that I modified ssh_steps.rb as below.

drb.containers -> containers.to_a

<pre>
Then /^I should( not)? see the "([^\"]*)" of "([^\"]*)" in the output$/ do |boolean, key, name|
  if (!boolean)
    @output.should =~ /#{$test_lab.containers.to_a[name][key.downcase.to_sym]}/i
  else
    @output.should_not =~ /#{$test_lab.containers.to_a[name][key.downcase.to_sym]}/i
  end
end
</pre>

**Comment by zpatten** [comment]
Nice catch; thanks!

**Comment by zpatten** [comment]
rc.15 is out with the fix

**Comment by YungSang** [comment]
Thanks!

**Pull request closed without merging**
