### PR TITLE
Removed cucumber-chef lines from gemspec, caused error with gem install.

### PR DESCRIPTION
**Pull request by talaris**
The lines of cucumber-chef as dependency in the gemspec was causing the creation of a new test lab to fail. Not sure if you would want to use the pull since it looked like from the commit this got generated from something else.

### CODE REVIEW

**Comment by zts** [comment]
I'm also seeing this problem, with the same impact - setting up a new test lab fails.
Using 'git bisect', I've identified 18b700a668dceac002f0494f0d7f511b1f26777c as the commit introducing this bug.

**Comment by manul** [comment]
A work around is to install chef-cucumber v 1.0.0 first

**Comment by Atalanta** [comment]
Sorry - will get to fixing this on Monday.

**Comment by mikebannister** [comment]
I think I'm having this problem but it's not any better when I apply the patch. My first guess is that because I'm using hosted chef my patched code isn't really getting used. Does that make sense? Any suggestions? Obviously pretty green here... but eager to get this working. Thanks, Mike

**Comment by dvolker** [comment]
I've managed to create a workaround and get "cucumber-chef setup" to complete successfully by modifying a couple files:

~/.rvm/gems/ruby-1.9.2-p180@chef/gems/cucumber-chef-1.0.*/cookbooks/cucumber-chef/recipes/test_lab.rb and testrunner.lb

and adding this "gem_package" block which will cause version 1.0.1 to be installed before/(instead of?) 1.0.2:

gem_package "cucumber-chef" do
  action :install
  version "1.0.1"
end

%w[cucumber-chef cucumber rspec].each do |gem|
    gem_package gem
end

**Comment by Atalanta** [comment]
This is proving to much less trivial than I'd hoped.  The gem installs, but tests are failing in unexpected ways.  Working on getting tests passing.  This won't be fixed before Monday - sorry.

**Comment by Atalanta** [comment]
Fixed in 1.0.3.

**Pull request closed without merging**
