### PR TITLE
Update WIKI.md

### PR DESCRIPTION
**Pull request by pikesley**
typo

### CODE REVIEW

**Comment by zpatten** [comment]
Why is the whole file showing every line was changed?

**Comment by pikesley** [comment]
Oh that's hideous. I edited it right in the browser, Github made a fork for me and offered me the pull-request buttons, I just submitted. Please feel free to ditch this.

**Comment by zpatten** [comment]
Ya it's just weird cause I can't tell what you changed.

**Comment by zpatten** [comment]
Silly GH!

**Comment by zpatten** [comment]
I'm all for fixing typos; please let me know what needs to be changed.

**Comment by pikesley** [comment]
I will give it a more thorough read-through tomorrow and get back to you :)

**Comment by zpatten** [comment]
Sure thing; it's very WIP, so expect a lot of bad spelling on my part lol!
 There is a reason I'm an engineer :)

**Comment by anujbiyani** [comment]
If you add `?w=1` to the end of the url when viewing the diff you can turn whitespace off (https://github.com/Atalanta/cucumber-chef/pull/105/files?w=1).

There must be something hidden in the file on every line that changed. Perhaps it's whitespace at the end of lines, or a \r became a \n, or tab characters turned into space characters.

**Comment by zpatten** [comment]
Reopen this back up if you need to; closing for now.

**Pull request closed without merging**
