### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by Aigeruth**
Changed Unix/Linux commands to Ruby alternatives.

### CODE REVIEW

**Comment by zpatten** [comment]
Nice work!

**Comment by zpatten** [comment]
@Aigeruth I haven't forgotten about you; going to release a patch version of the gem with your changes here in a few.

**Comment by Aigeruth** [comment]
@zpattern No problem. It still doesn't work on Windows, because [ztk/lib/ztk/command.rb](https://github.com/zpatten/ztk/blob/master/lib/ztk/command.rb#L97) uses Process.Fork() and this is not implemented on Windows. IMHO it should use [childprocess](https://github.com/jarib/childprocess) like Vagrant does. I made a dirty version with childprocess, but I didn't have time to test it properly. That is why I haven't sent PR yet.

**Comment by zpatten** [comment]
I am not opposed to this; as long as we can maintain the same functionality.  I'll take a look.  If you have some code already done that you can gist/PR me I would appreciate it (anything that saves me time).

**Comment by zpatten** [comment]
@Aigeruth Go ahead and open an issue over on my ZTK repo for this.

**Pull request merged**
